### PR TITLE
fix: Start page looses focus with pinned tabs

### PR DESCRIPTION
**Pull request by ericawright**
r: @bwinton 

change focus to first unpinned tab on startup

fixes: #605

### CODE REVIEW

**Comment by bwinton** [comment]
I don't think this is the right thing to do…  If I have selected a pinned tab, and close and re-open Firefox, I expect to be on that pinned tab, not on the first unpinned tab.

(I'm not sure what behaviour the original bug was expecting, but it seems like Firefox retains the last selected tab, not what the reporter was suggesting.)

**Comment by ericawright** [comment]
I was able to duplicate the original bug multiple times. If you have a pinned tab - at least one - open a brand new firefox (no memory of what was selected) it will select the pinned tab rather than the new tab page.

**Comment by bwinton** [comment]
I'm a little confused, then.  Can I get a set of steps to reproduce this for myself, and how the behaviour in Firefox without Tab Center differs from with Tab Center?

**Comment by ericawright** [comment]
Okay STR:
make a new profile 'test'
run firefox and pin at least one tab
quit firefox cmd-q
run TC with `jpm run -b -p test`

ER:
the pinned tab is at the top, and the start page is selected

AR:
the pinned tab is selected, the start page opens below it, but is not selected

**Comment by bwinton** [comment]
(As an update, this was different because I've got the "show windows and tabs from last time" option set.  Erica is going to make sure this code works correctly in both those cases. 🙂)

**Pull request merged**
