### PR TITLE
fix: Disappearing labels

### PR DESCRIPTION
**Pull request by ericawright**
r: @bwinton 

- thumbnails update on redraw
- labels inherit value from parent

### CODE REVIEW

**Comment by bwinton** [comment]
>having trouble positioning and sizing the favicon/spinner. was happy to discover stack but the icon is still being squished.

Hmm, I'll check it out and see what I can figure out.  (Although, we don't _have_ to add the stack element.  Everything should just line up correctly without it, right?)

> any ideas on how to get that background dotted line image in? src does not have the same ability as background-image to list multiple sources.

Add a second image to the stack containing the dotted line, and make sure it's underneath the thumbnail?  Also, if we go with the canvas element I suggested in Slack, we might be able to just draw the dotted line when we need it, and not when we don't…

**Comment by ericawright** [comment]
> Hmm, I'll check it out and see what I can figure out. (Although, we don't have to add the stack element. Everything should just line up correctly without it, right?)

nope :) because the only way to have the anon element inherit the image from the parent is to not have it be a background-image anymore and make it an src on a real image. And of course I can't have an image inside another image, so I'm using stack.

**Comment by bwinton** [comment]
So, I played around with it for a while, but couldn't get it working.  As an alternate approach, what about not using a stack, and making the tab-icon-image (and throbber) `position: absolute` instead?

**Comment by ericawright** [comment]
`position: absolute` doesn't seem to work with XUL.

I've changed it now to use a constructor, give it a try.

**Pull request merged**
