### PR TITLE
Mention jpm in the readme

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
The README file says "if you want to get involved and maybe fix some bugs." with a link to the issue list, but says nothing about how to go about doing so. The CONTRIBUTING file seem to only be relevant from the point where one is ready to make a pull request.

This is a start, there is probably more to say around this.

**Comment by bwinton** [comment]
Awesome contribution, thank you!  😃

**Comment by SimonSapin** [comment]
It looks like fixing #551 is probably a matter of reverting commit 396f290db98a100ee2e73ad052470dd0434aa142 from #508. But since #551 is already open, I was expecting to see some positive comment on it from the person who made that commit or another maintainer before submitting a PR seemed appropriate.

**Comment by bwinton** [comment]
It sort of is, but I think there are some edge cases that need handling…  (There have been a lot of reports of double-scrollbars, and having the scrollbar overlap the close button, and stuff.  And it's unclear whether we want the arrows as well as the scrollbar, or only the scrollbar.)

**Pull request merged**
