### PR TITLE
Change how TabCenter CSS is loaded & Clean up TabCenter CSS

### PR DESCRIPTION
**Pull request by nt1m**
Summary of changes:
- Change how TabCenter CSS is loaded
Before this PR, everything TabCenter sets with CSS is more important than everything else (on top of the chain). Now, TabCenter just follows the normal rules of CSS priority. This simple change allows customization-savy users to override everything else, while still giving importance to TabCenter's CSS.

- Clean up TabCenter CSS
Removed redundant rules, invalid selectors (that were previously simply ignored).
The gradient that TabCenter removes in https://github.com/bwinton/TabCenter/commit/446c3fd1fefbb7a4f97ae6a8e2360520efe887b7 is actually from https://github.com/bwinton/TabCenter/blob/master/skin/osx.css#L85
I've fixed that redundancy as well.

### CODE REVIEW

**Comment by nt1m** [comment]
@ericawright Can you review this please ?

**Comment by nt1m** [comment]
Note that there are no user-visible changes, tested against lightweight themes and the devedition theme.

**Comment by ericawright** [comment]
a few issues:

f11-fullscreen in windows (with a sidebar open - margin remains):
screen shot 2016-10-05 at 10 33 20 am

find-input on mac (not lined up):
screen shot 2016-10-05 at 10 25 18 am

**Comment by ericawright** [comment]
(also, please run `npm run lint` before I can merge)

**Comment by nt1m** [comment]
@ericawright I don't have a windows box unfortunately. I've fixed the searchbox issue though.

**Comment by ericawright** [comment]
thanks @nt1m. I've realized that the windows issue is related to something else.

**Pull request merged**
