### PR TITLE
move <strictCompatibility> to parent

### PR DESCRIPTION
**Pull request by clouserw**
credit to Spoji on IRC for catching this

### CODE REVIEW

**Comment by ericawright** [comment]
Unfortunately, it didn't seem to change anything. I can still install it with an XPI on Nightly v55.

**Comment by ericawright** [comment]
I wonder if installing with the xpi could be a unique case and not an indicator of the restriction's success?

**Comment by clouserw** [comment]
does it still enable and work?

**Comment by ericawright** [comment]
yes, it still enables and still works

**Comment by SoftVision-PaulOiegas** [comment]
@ericawright had the same thought about the unique case when I asked about how the restriction works in the PR #1082. If you guys come up with a solution, let us know and we'll help testing it.

**Comment by ericawright** [comment]
it turns out that the entire `update.rdf` file is unused. And this has to be done through the `package.json` file.

**Pull request closed without merging**
