### PR TITLE
feature: toggle between side tabs and top tabs

### PR DESCRIPTION
**Pull request by ericawright**
r: @bwinton, @phlsa 

- click the top tabs icon to restore tabs to the top, click the TC icon to bring back side tabs.
- applies to each window separately.

notes: 
- ~~still need to test on other OSs, yup windows needs style work!~~
- ~~I still need to test customize mode~~ it can not be customized (gets greyed-out)
- ~~still need to add stats~~ TODO later
- ~~still need to test what happens when the hotkeys are used~~ nothing happens - no errors
- ~~not sure I like the position of the top-tabs button as I expect the "new tab" button will be more often used and it is taking a very valuable corner.~~ moving it
- ~~need assets for dark theme~~

fixes: #691

### CODE REVIEW

**Comment by phlsa** [comment]
Is there an XPI that I can use for testing? Thanks!

**Comment by ericawright** [comment]
XPI for testing:
https://www.dropbox.com/s/ne5i2wu62a0j4hn/tabcentertest1%40mozilla.com-1.26.0.xpi?dl=0

**Comment by phlsa** [comment]
Thanks Erica! The toggling works great!

There are a few issues (tested on Windows), from most to least severe:

- The button is there, but it has no icon (in either state). Also, the icon on the auto-collapse button of TC has disappeared.
- I got stuck in one state at some point. I was in side tabs mode and the button stopped working. After a few restarts and wild clicking, the issue has disappeared. I don't know how to reproduce this at the moment.
- The hover state of the new tab button in side tabs mode has some additional borders on either side now. It looks like it is somehow inheriting styles from buttons placed in the tab bar
- The hover state of the toggle and the collapse button have reverted to the Windows default in this build.

I'll keep using it and let you know if I find anything else!

**Comment by ericawright** [comment]
screen shot 2016-10-18 at 11 17 51 am
re: button placement on windows. It does not seem possible to shift the button further to the right...

**Comment by ericawright** [comment]
@phlsa I believe changing the bit of CSS that I did has fixed all of the issues you brought up, other than getting stuck in one mode.

**Comment by phlsa** [comment]
Oh nice! Could you shoot me another XPI?

**Comment by ericawright** [comment]
@phlsa the same link works :)

**Comment by phlsa** [comment]
Thank you! The change fixed almost everything :)
The rest is summarized here:
tc-glitches

**Comment by ericawright** [comment]
@phlsa can you get me inverted icons?

**Comment by phlsa** [comment]
Here's the full icon set
[tc-top-white.zip](https://github.com/bwinton/TabCenter/files/536900/tc-top-white.zip)

**Comment by ericawright** [comment]
@phlsa do you have a further opinion on where to put this toggle button?

I want to have my new tab button accessible in this case:
screen shot 2016-10-18 at 3 43 30 pm

Blake and I just discussed perhaps adding it where addon icons go in the nav-bar and then switching the icon on click.

**Comment by ericawright** [comment]
works on Ubuntu Linux, plus bonus animation! 😆 

oct-18-2016 16-44-55

**Comment by bwinton** [comment]
(I'm waiting for @phlsa's comments on better places to put the side/top toggle button before I review this…)

**Comment by phlsa** [comment]
Yeah, you're right about the positioning. It would have made more sense if we could have put the icon to the left of the tab strip in tabs on top mode.

We can put the button between the search field and the collapse button instead:
tc

This is probably not 100% ideal either, but fine for an MVP without needing to do a more thorough design change :)

**Pull request merged**
