### PR TITLE
Fix strings display for sidebarShrink/Open

### PR DESCRIPTION
**Pull request by yfdyh000**
This issue screenshots:

### CODE REVIEW

**Comment by SoftVision-CiprianMuresan** [comment]
Hey @yfdyh000, this issue is already fixed in the latest master, see [Erica's comment in #866](https://github.com/bwinton/TabCenter/issues/866#issuecomment-269812820).

**Comment by yfdyh000** [comment]
@ericawright I can't find the commit for fixed.

**Comment by yfdyh000** [comment]
Seems be https://github.com/bwinton/TabCenter/commit/010b1485fb6b30d30336f5c70ebed53a8ba6c5a1.

**Comment by ericawright** [comment]
@yfdyh000 yes, that's the one

**Pull request closed without merging**
