### PR TITLE
fix: Add a hotkey to toggle focus the tab searchbox.  🔥

### LINKED ISSUE #95: feature request: keyboard shortcut to open and close the drawer without needing to mouse hover
:)

again please close if you would not like to support this or it's being tracked elsewhere

### PR DESCRIPTION
**Pull request by bwinton**
Used `ctrl-shift-k`/`cmd-shift-k` to be like the searchbar.
Needed to add the extra attribute so that we would do sane things when the mouse was or wasn't in the sidebar when toggling.

Reviewer: @ericawright
Fixes #95.

### CODE REVIEW

**Comment by ericawright** [comment]
After it auto-opens, it does not close again. 
aug-18-2016 14-39-20

**Comment by bwinton** [comment]
Yeah, it's "hard" to tell when we're done searching, so I've left it as "cmd-shift-k" is a toggle.  We'll definitely need to mention this in the notes.

(It can't be onblur, cause we might be switching tabs, so I'ld need to add some sort of overlay over the content, but that seems kinda ugly.  I think we can leave it this way for now as long as we call it a toggle-key-that-happens-to-focus-the-search-box…  😉)

**Comment by ericawright** [comment]
Okay, if this is considered a toggle to open the drawer then that behavior makes sense. I still feel that it should not happen if the drawer is already pinned open, and the state should be reset on clicking the top-right icon.

**Comment by bwinton** [comment]
Done, kinda.  (It's mostly a toggle to open the drawer, but if it's pinned open we might as well use it to also focus the tabsearch bar.)

**Comment by ericawright** [comment]
One last thing. At this point the hotkey will only toggle closed if #find-input is focused. so I have to hit the hotkeys twice in order to close the drawer if I have made use of my search and clicked elsewhere

**Comment by bwinton** [comment]
Fixed!  :)

(Also, thanks for finding all these things!)

**Pull request merged**
